SomaLogic/SomaDataIO

- Makefile
- _pkgdown.yml
- tests/testthat/_snaps/S3-print.md
- tests/testthat/test-SeqId.R
- Cleaned up testing suite for consistency and format
> Minor tweaks to unit tests for SeqIds

- .github/workflows/pkgdown.yaml
| Department     | Reviewer      | Change Type          |
|:-------------- |:------------- | -------------------- |
| Bioinformatics | @stufield     | Code, bugs, features |
| Info. Sec.     | @trhein       | LICENSE              |
| Legal          | @SLbmangum    | LICENSE              | 
| Marketing      | @kmurugesan14 | Documentation        |
| Regulatory     | @nmcnabbSL    | Documentation        |
------------
> Add build-pkgdown branch to GHA

- vignettes/linear-regression.Rmd
- vignettes/two-group-comparison.Rmd
Cleaned up some of the vignettes now that they're 3 separate isolated analyses. Some of the objects/verbiage didn't make sense anymore.
> Clean up redundancy in split vignettes

- README.Rmd
- README.md
- vignettes/loading-and-wrangling.Rmd
Tweak the load/wrangle vignette to include `debug = TRUE` option to `read_adat()`
> Tweak vignette readme

- .github/workflows/test-coverage.yaml
- R/getTargetNames.R
- tests/testthat/_snaps/getTargetNames.md
- tests/testthat/test-getTargetNames.R
- tests/testthat/test-is-seqFormat.R
> Unit test is seq format

- R/diffAdats.R
- R/getAnalyteInfo.R
- tests/testthat/test-getAnalyteInfo.R
- tests/testthat/test-is-seqFormat.R
- simplify function (no more need for check warning
- increased coverage for testing suite
> Simplify and coverage for getAnalyteInfo()

- NEWS.md
- _pkgdown.yml
- inst/WORDLIST
- vignettes/cli-merge-tool.Rmd
- vignettes/loading-and-wrangling.Rmd
- new CLI merge tool to add new clinical data to existing ADAT file
- closes #45
> Add vignette for new command line merge tool

- README.Rmd
- README.md
- data-raw/SomaScanObjects.R
Missing `(` in SomaScanObjects.R script
- in the `if` statement
- fixes #40
> Fix missing closing parens in SomaScanObjects.R

- .github/workflows/document.yaml
- .github/workflows/pkgdown.yaml
- .github/workflows/render-readme.yaml
- .github/workflows/repo-release-sync.yaml
- .github/workflows/test-coverage.yaml
- allow for manual triggering of branch
> Update pkgdown.yaml GitHub Action workflow trigger

- .Rbuildignore
- .gitignore
- R/loadAdatsAsList.R
- R/utils.R
- R/write-adat.R
- man/getAnalytes.Rd
- man/loadAdatsAsList.Rd
Bugfix for single SOMAmer ADATs
- fixes #51
> Bugfix write adat apply

- _pkgdown.yml
Cleaned up footer for all pkgdown pages
> Cleaned up _pkgdown.yml

- LICENSE
- LICENSE.md
- README.Rmd
- now ensures the `LICENSE.md` file is recognized by GitHub repository GUI
- some legal language moved from `LICENSE.md` file into the README as suggested by https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository
Please check the relevant box(es):
| Department     | Reviewer      | Change Type          |
|:-------------- |:------------- | -------------------- |
| Bioinformatics | @stufield     | Code, bugs, features |
| Info. Sec.     | @trhein       | LICENSE              |
| Legal          | @SLbmangum    | LICENSE              | 
| Marketing      | @kmurugesan14 | Documentation        |
| Regulatory     | @nmcnabbSL    | Documentation        |
> Fix LICENSE syntax and update README

- _pkgdown.yml
This PR updates the `pkgdown` YAML to include the newly exposed functions that were previously in the `sysdata.rda` file.
They now need to be documented and have a pkgdown website page.
This should have been part of #59
> Update _pkgdown.yml with new sysdata functions

- LICENSE.md
Needed to make the GitHub GUI recognize the LICENSE file
- now uses standard template to enable for auto-recognition by GitHub GUI sidebar
> Standardize LICENSE.md file

- _pkgdown.yml
- General description of this pull request ...
- fix for adding `params` entry in the `_pkgdown.yml` file; website/pages should now build
> Fix `pkgdown.yml` params; website pages to build

- R/read-adat.R
- README.Rmd
- README.md
- man/read_adat.Rd
- vignettes/cli-merge-tool.Rmd
- vignettes/loading-and-wrangling.Rmd
- feedback was incorporated into docs, vignettes, and README
> Modify docs based on feedback from external customers

- NEWS.md
- R/lift-adat.R
- R/merge-clin.R
- inst/WORDLIST
- man/lift_adat.Rd
- man/merge_clin.Rd
- vignettes/SomaDataIO.Rmd
- Get NEWS.md file ready for release of 6.1.0
- closes #75
> Update `NEWS.md` for release6.1.0

- R/is-intact-attr.R
- R/lift-adat.R
- R/read-adat.R
- R/z-deprecated.R
- man/SomaDataIO-deprecated.Rd
- man/figures/lifecycle-deprecated.svg
- man/figures/lifecycle-soft-deprecated.svg
- man/figures/lifecycle-stable.svg
- man/figures/lifecycle-superseded.svg
- man/getAnalyteInfo.Rd
- man/getAnalytes.Rd
- man/is_intact_attr.Rd
- man/lift_adat.Rd
- man/read_adat.Rd
- added new badges to docs
- updated stages and re-directs
> Prepare lifecycle stages and docs pre 6.1.0 release

- DESCRIPTION
- R/lift-adat.R
- cran-comments.md
- man/lift_adat.Rd
> Submit CRAN 6.1.0

- DESCRIPTION
- man/SomaDataIO-package.Rd
- vignettes/SomaDataIO.Rmd
> Minor docs fixes

- README.Rmd
- README.md
- now shows 'downloads' per month over total downloads
- closes #109
> Update README badge

- .github/workflows/pkgdown.yaml
- added write permission to GHA pkgdown job workflow yaml file
> Update GHA pkgdown.yaml deploy permissions

- R/loadAdatsAsList.R
- R/pivotExpressionSet.R
- R/s3-print-soma-adat.R
- man/loadAdatsAsList.Rd
- man/pivotExpressionSet.Rd
- man/soma_adat.Rd
- fixed note from remote windows check related to Rd \link{} targets missing package anchors
> Add missing package anchors to .Rd files

- .github/workflows/rhub.yaml
- added rhub.yaml configuration file to .github/workflows/
- default configuration from rhub_setup() function to comply with rhub v2
> Setup github workflow for rhub v2

- DESCRIPTION
- NEWS.md
- R/adat2eSet.R
- R/pivotExpressionSet.R
- cran-comments.md
- inst/WORDLIST
- man/adat2eSet.Rd
- man/pivotExpressionSet.Rd
- tests/testthat/test-adat2eSet.R
- tests/testthat/test-pivotExpressionSet.R
> Submit CRAN 6.2.0

- vignettes/articles/pre-processing.Rmd
- updated labels on flagged RowCheck image to FLAG
- adjusted widths of acceptance criteria images
> Update pre-processing vignette flag images

- NEWS.md
- R/calcOutlierMap.R
- R/plotMap.R
- R/preProcessAdat.R
- cran-comments.md
- inst/WORDLIST
- man/calcOutlierMap.Rd
- man/plot.Map.Rd
- man/preProcessAdat.Rd
- vignettes/articles/pre-processing.Rmd
- simplified examples of calcOutlierMap() and s3 methods to reduce execution times
- fixed spelling errors and updated WORDLIST
- updated NEWS.md and cran-comments.md
- addresses items in #146
> Release candidate 6.3.0

- DESCRIPTION
- NEWS.md
> Increment version number to 6.3.0

- .github/pull_request_template.md
- removed out-of-date tagged reviewers by department from pull_request_template.md
> Update tags in pull_request_template.md

- vignettes/articles/pre-processing.Rmd
- vignettes/articles/stat-binary-classification.Rmd
- vignettes/articles/stat-linear-regression.Rmd
- vignettes/articles/stat-three-group-analysis-anova.Rmd
- vignettes/articles/stat-two-group-comparison.Rmd
- move library() calls loading third-party packages to new code chunk that now appears in analysis workflow articles
> Show pkg loading in stat workflow vignettes
